# This pipeline check everyday at 12:00pm if the application is currently
# running into a self-hosted runner
name: Current Status

# Configure pipeline to execute using cron schedule
# (https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule)
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  push: # WIP: To check timeout-minutes parameter into job field

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  queued-timeout:
    runs-on: ubuntu-latest
    steps:
      - name: Workaround to detect any queued pipeline
        run: |
          # Original idea: https://github.com/orgs/community/discussions/50926#discussioncomment-6161198
          # Wait 5min
          sleep 5m
          # Check if there is any queued pipeline into this repository and pass the workflow ID to cancel.
          gh --repo ${{ github.repository }}  run list --status queued --json databaseId -q .[].databaseId | xargs gh --repo ${{ github.repository }} run cancel
  check-status:
    runs-on: self-hosted
    steps:
      - name: Check if flashcardbot container is running
        run: |
          docker container inspect flashcardbot &> /dev/null
    timeout-minutes: 2
